<a href="https://colab.research.google.com/github/Rahul786Patidar/Lending_company/blob/main/Lending_company.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
data = pd.read_csv('/content/drive/MyDrive/DIGICHROME/Lending-company.csv')
data

,LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0,1,LoanID_1,Product B,Female,Location 3,Region 2,17600.0,04-07-2018,2200,45,365,3221,4166,14621,Active
1,2,LoanID_2,Product D,Female,Location 6,Region 6,NaN,02-01-2019,2200,45,365,3161,4096,16041,Active
2,3,LoanID_3,Product B,Male,Location 8,Region 3,16600.0,08-12-2016,1000,45,365,2260,3205,16340,NaN
3,4,LoanID_4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
4,5,LoanID_5,Product B,Female,Location 34,Region 3,21250.0,28-10-2017,2200,55,365,3570,4745,14720,Active
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038,1039,LoanID_1039,Product B,Male,Location 73,Region 6,17300.0,29-12-2018,2200,45,365,3251,4743,16617,Finished Payment
1039,1040,LoanID_1040,Product A,Male,Location 82,Region 1,NaN,28-03-2018,2200,45,365,4090,5582,16617,Finished Payment
1040,1041,LoanID_1041,Product A,NotSpecified,Location 11,Region 4,17300.0,26-04-2018,2200,45,365,4051,5143,16617,Finished Payment
1041,1042,LoanID_1042,Product B,Female,Location 26,Region 6,16300.0,25-10-2016,1000,45,365,1930,3462,15617,Finished Payment
1042,1043,LoanID_1043,Product A,NotSpecified,Location 94,Region 6,17300.0,15-05-2019,2200,45,365,4451,4743,16617,Finished Payment

In [4]:
data.head()

,LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
0,1,LoanID_1,Product B,Female,Location 3,Region 2,17600.0,04-07-2018,2200,45,365,3221,4166,14621,Active
1,2,LoanID_2,Product D,Female,Location 6,Region 6,NaN,02-01-2019,2200,45,365,3161,4096,16041,Active
2,3,LoanID_3,Product B,Male,Location 8,Region 3,16600.0,08-12-2016,1000,45,365,2260,3205,16340,NaN
3,4,LoanID_4,Product A,Male,Location 26,Region 2,17600.0,NaN,2200,45,365,3141,4166,16321,Active
4,5,LoanID_5,Product B,Female,Location 34,Region 3,21250.0,28-10-2017,2200,55,365,3570,4745,14720,Active

In [5]:
data.tail()

,LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360,LoanStatus
1038,1039,LoanID_1039,Product B,Male,Location 73,Region 6,17300.0,29-12-2018,2200,45,365,3251,4743,16617,Finished Payment
1039,1040,LoanID_1040,Product A,Male,Location 82,Region 1,NaN,28-03-2018,2200,45,365,4090,5582,16617,Finished Payment
1040,1041,LoanID_1041,Product A,NotSpecified,Location 11,Region 4,17300.0,26-04-2018,2200,45,365,4051,5143,16617,Finished Payment
1041,1042,LoanID_1042,Product B,Female,Location 26,Region 6,16300.0,25-10-2016,1000,45,365,1930,3462,15617,Finished Payment
1042,1043,LoanID_1043,Product A,NotSpecified,Location 94,Region 6,17300.0,15-05-2019,2200,45,365,4451,4743,16617,Finished Payment

In [6]:
data.shape

(1043, 15)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1043 entries, 0 to 1042
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   LoanID          1043 non-null   int64
 1   StringID        1043 non-null   object
 2   Product         1043 non-null   object
 3   CustomerGender  1043 non-null   object
 4   Location        1043 non-null   object
 5   Region          1042 non-null   object
 6   TotalPrice      1018 non-null   float64
 7   StartDate       1042 non-null   object
 8   Deposit         1043 non-null   int64
 9   DailyRate       1043 non-null   int64
 10  TotalDaysYr     1043 non-null   int64
 11  AmtPaid36       1043 non-null   int64
 12  AmtPaid60       1043 non-null   int64
 13  AmtPaid360      1043 non-null   int64
 14  LoanStatus      1006 non-null   object
dtypes: float64(1), int64(7), object(7)
memory usage: 122.4+ KB

In [8]:
data.describe()

,LoanID,TotalPrice,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360
count,1043.000000,1018.000000,1043.000000,1043.000000,1043.0,1043.000000,1043.000000,1043.000000
mean,522.000000,19562.843811,2528.092042,50.834132,365.0,3901.857143,5214.393097,17122.131352
std,301.232468,5955.588065,1504.467724,11.567390,0.0,2537.597667,2850.327133,5910.916736
min,1.000000,13475.000000,1000.000000,30.000000,365.0,-2770.000000,-2945.000000,650.000000
25%,261.500000,16300.000000,2200.000000,45.000000,365.0,2840.500000,3822.000000,15560.500000
50%,522.000000,17600.000000,2200.000000,45.000000,365.0,3420.000000,4742.000000,16617.000000
75%,782.500000,20950.000000,2200.000000,55.000000,365.0,5075.500000,6393.000000,19977.500000
max,1043.000000,70225.000000,8000.000000,150.000000,365.0,18851.000000,22143.000000,65001.000000

In [9]:
data.corr()

<ipython-input-9-c44ded798807>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  data.corr()

,LoanID,TotalPrice,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360
LoanID,1.000000,-0.065548,-0.011576,-0.061056,NaN,0.160149,0.237748,0.239287
TotalPrice,-0.065548,1.000000,0.738309,0.983060,NaN,0.618479,0.641597,0.768294
Deposit,-0.011576,0.738309,1.000000,0.642923,NaN,0.743106,0.725999,0.638532
DailyRate,-0.061056,0.983060,0.642923,1.000000,NaN,0.539393,0.569381,0.737966
TotalDaysYr,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AmtPaid36,0.160149,0.618479,0.743106,0.539393,NaN,1.000000,0.950010,0.691491
AmtPaid60,0.237748,0.641597,0.725999,0.569381,NaN,0.950010,1.000000,0.749672
AmtPaid360,0.239287,0.768294,0.638532,0.737966,NaN,0.691491,0.749672,1.000000

In [10]:
data.isnull().sum()

LoanID             0
StringID           0
Product            0
CustomerGender     0
Location           0
Region             1
TotalPrice        25
StartDate          1
Deposit            0
DailyRate          0
TotalDaysYr        0
AmtPaid36          0
AmtPaid60          0
AmtPaid360         0
LoanStatus        37
dtype: int64

In [11]:
data.fillna(value=0, inplace=True)  # Replaces nulls with 0
data["TotalPrice"].fillna(value=data["TotalPrice"].mean(), inplace=True)  # Replaces nulls with mean

In [12]:
data.isnull().sum()

LoanID            0
StringID          0
Product           0
CustomerGender    0
Location          0
Region            0
TotalPrice        0
StartDate         0
Deposit           0
DailyRate         0
TotalDaysYr       0
AmtPaid36         0
AmtPaid60         0
AmtPaid360        0
LoanStatus        0
dtype: int64

In [13]:
data.columns

Index(['LoanID', 'StringID', 'Product', 'CustomerGender', 'Location', 'Region',
       'TotalPrice', 'StartDate', 'Deposit', 'DailyRate', 'TotalDaysYr',
       'AmtPaid36', 'AmtPaid60', 'AmtPaid360', 'LoanStatus'],
      dtype='object')

In [14]:
data.dtypes

LoanID              int64
StringID           object
Product            object
CustomerGender     object
Location           object
Region             object
TotalPrice        float64
StartDate          object
Deposit             int64
DailyRate           int64
TotalDaysYr         int64
AmtPaid36           int64
AmtPaid60           int64
AmtPaid360          int64
LoanStatus         object
dtype: object

In [15]:
data['Region']

0       Region 2
1       Region 6
2       Region 3
3       Region 2
4       Region 3
          ...
1038    Region 6
1039    Region 1
1040    Region 4
1041    Region 6
1042    Region 6
Name: Region, Length: 1043, dtype: object

**Find Categorical Variables**

In [16]:
# find categorical variables

categorical = [var for var in data.columns if data[var].dtype=='O']

print('There are {} categorical variables\n'.format(len(categorical)))

print('The categorical variables are :\n\n', categorical)

There are 7 categorical variables

The categorical variables are :

 ['StringID', 'Product', 'CustomerGender', 'Location', 'Region', 'StartDate', 'LoanStatus']

In [17]:
# view the categorical variables

data[categorical].head()

,StringID,Product,CustomerGender,Location,Region,StartDate,LoanStatus
0,LoanID_1,Product B,Female,Location 3,Region 2,04-07-2018,Active
1,LoanID_2,Product D,Female,Location 6,Region 6,02-01-2019,Active
2,LoanID_3,Product B,Male,Location 8,Region 3,08-12-2016,0
3,LoanID_4,Product A,Male,Location 26,Region 2,0,Active
4,LoanID_5,Product B,Female,Location 34,Region 3,28-10-2017,Active

**Explore problems within categorical variables**

In [18]:
# check missing values in categorical variables

data[categorical].isnull().sum()

StringID          0
Product           0
CustomerGender    0
Location          0
Region            0
StartDate         0
LoanStatus        0
dtype: int64

Now, I will check the frequency counts of categorical variables.

In [19]:
# view frequency counts of values in categorical variables

for var in categorical:

    print(data[var].value_counts())

LoanID_1       1
LoanID_686     1
LoanID_688     1
LoanID_689     1
LoanID_690     1
              ..
LoanID_353     1
LoanID_354     1
LoanID_355     1
LoanID_356     1
LoanID_1043    1
Name: StringID, Length: 1043, dtype: int64
Product B    400
Product A    354
Product C    137
Product D    130
Product E     20
Product F      2
Name: Product, dtype: int64
Male            624
Female          333
NotSpecified     86
Name: CustomerGender, dtype: int64
Location 25     31
Location 30     27
Location 3      24
Location 26     23
Location 22     21
                ..
Location 168     1
Location 136     1
Location 99      1
Location 132     1
Location 181     1
Name: Location, Length: 296, dtype: int64
Region 6     326
Region 3     206
Region 2     188
Region 1     131
Region 4      62
Region 7      47
Region 5      30
Region 8      10
Region 15      8
Region 10      7
Region 12      6
Region 9       6
Region 13      5
Region 14      3
Region 17      3
Region 16      2
0              1
Region 11      1
Region 18      1
Name: Region, dtype: int64
23-04-2019    7
27-03-2019    5
24-02-2018    5
22-04-2020    5
11-09-2019    5
             ..
08-09-2019    1
06-05-2019    1
19-12-2017    1
18-07-2020    1
26-04-2018    1
Name: StartDate, Length: 743, dtype: int64
Finished Payment    534
Active              460
0                    37
Blocked              12
Name: LoanStatus, dtype: int64

In [20]:
# view frequency distribution of categorical variables

for var in categorical:

    print(data[var].value_counts()/np.float(len(data)))

LoanID_1       0.000959
LoanID_686     0.000959
LoanID_688     0.000959
LoanID_689     0.000959
LoanID_690     0.000959
                 ...
LoanID_353     0.000959
LoanID_354     0.000959
LoanID_355     0.000959
LoanID_356     0.000959
LoanID_1043    0.000959
Name: StringID, Length: 1043, dtype: float64
Product B    0.383509
Product A    0.339406
Product C    0.131352
Product D    0.124640
Product E    0.019175
Product F    0.001918
Name: Product, dtype: float64
Male            0.598274
Female          0.319271
NotSpecified    0.082454
Name: CustomerGender, dtype: float64
Location 25     0.029722
Location 30     0.025887
Location 3      0.023011
Location 26     0.022052
Location 22     0.020134
                  ...
Location 168    0.000959
Location 136    0.000959
Location 99     0.000959
Location 132    0.000959
Location 181    0.000959
Name: Location, Length: 296, dtype: float64
Region 6     0.312560
Region 3     0.197507
Region 2     0.180249
Region 1     0.125599
Region 4     0.059444
Region 7     0.045062
Region 5     0.028763
Region 8     0.009588
Region 15    0.007670
Region 10    0.006711
Region 12    0.005753
Region 9     0.005753
Region 13    0.004794
Region 14    0.002876
Region 17    0.002876
Region 16    0.001918
0            0.000959
Region 11    0.000959
Region 18    0.000959
Name: Region, dtype: float64
23-04-2019    0.006711
27-03-2019    0.004794
24-02-2018    0.004794
22-04-2020    0.004794
11-09-2019    0.004794
                ...
08-09-2019    0.000959
06-05-2019    0.000959
19-12-2017    0.000959
18-07-2020    0.000959
26-04-2018    0.000959
Name: StartDate, Length: 743, dtype: float64
Finished Payment    0.511985
Active              0.441035
0                   0.035475
Blocked             0.011505
Name: LoanStatus, dtype: float64

<ipython-input-20-fae9ae22feae>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(data[var].value_counts()/np.float(len(data)))
<ipython-input-20-fae9ae22feae>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(data[var].value_counts()/np.float(len(data)))
<ipython-input-20-fae9ae22feae>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(data[var].value_counts()/np.float(len(data)))
<ipython-input-20-fae9ae22feae>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(data[var].value_counts()/np.float(len(data)))
<ipython-input-20-fae9ae22feae>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(data[var].value_counts()/np.float(len(data)))
<ipython-input-20-fae9ae22feae>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(data[var].value_counts()/np.float(len(data)))
<ipython-input-20-fae9ae22feae>:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(data[var].value_counts()/np.float(len(data)))

In [21]:
# check labels in LoanStatus variable

data.LoanStatus.unique()

array(['Active', 0, 'Blocked', 'Finished Payment'], dtype=object)

In [22]:
data.LoanStatus.value_counts()

Finished Payment    534
Active              460
0                    37
Blocked              12
Name: LoanStatus, dtype: int64

In [23]:
# check labels in StringID variable

data.StringID.unique()

array(['LoanID_1', 'LoanID_2', 'LoanID_3', ..., 'LoanID_1041',
       'LoanID_1042', 'LoanID_1043'], dtype=object)

In [24]:
# check frequency distribution of values in StringID variable

data.StringID.value_counts()

LoanID_1       1
LoanID_686     1
LoanID_688     1
LoanID_689     1
LoanID_690     1
              ..
LoanID_353     1
LoanID_354     1
LoanID_355     1
LoanID_356     1
LoanID_1043    1
Name: StringID, Length: 1043, dtype: int64

In [25]:
# replace '?' values in StringID variable with `NaN`


data['StringID'].replace('?', np.NaN, inplace=True)

In [26]:
# again check the frequency distribution of values in workclass variable

data.StringID.value_counts()

LoanID_1       1
LoanID_686     1
LoanID_688     1
LoanID_689     1
LoanID_690     1
              ..
LoanID_353     1
LoanID_354     1
LoanID_355     1
LoanID_356     1
LoanID_1043    1
Name: StringID, Length: 1043, dtype: int64

In [27]:
data[categorical].isnull().sum()

StringID          0
Product           0
CustomerGender    0
Location          0
Region            0
StartDate         0
LoanStatus        0
dtype: int64

**cardinality - Number of labels**

In [28]:
# check for cardinality in categorical variables

for var in categorical:

    print(var, ' contains ', len(data[var].unique()), ' labels')

StringID  contains  1043  labels
Product  contains  6  labels
CustomerGender  contains  3  labels
Location  contains  296  labels
Region  contains  19  labels
StartDate  contains  743  labels
LoanStatus  contains  4  labels

**Explore Numerical Variables**

In [29]:
# find numerical variables

numerical = [var for var in data.columns if data[var].dtype!='O']

print('There are {} numerical variables\n'.format(len(numerical)))

print('The numerical variables are :', numerical)

There are 8 numerical variables

The numerical variables are : ['LoanID', 'TotalPrice', 'Deposit', 'DailyRate', 'TotalDaysYr', 'AmtPaid36', 'AmtPaid60', 'AmtPaid360']

In [30]:
# view the numerical variables

data[numerical].head()

,LoanID,TotalPrice,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360
0,1,17600.0,2200,45,365,3221,4166,14621
1,2,0.0,2200,45,365,3161,4096,16041
2,3,16600.0,1000,45,365,2260,3205,16340
3,4,17600.0,2200,45,365,3141,4166,16321
4,5,21250.0,2200,55,365,3570,4745,14720

In [31]:
# check missing values in numerical variables

data[numerical].isnull().sum()

LoanID         0
TotalPrice     0
Deposit        0
DailyRate      0
TotalDaysYr    0
AmtPaid36      0
AmtPaid60      0
AmtPaid360     0
dtype: int64

In [32]:
data['LoanStatus']

0                 Active
1                 Active
2                      0
3                 Active
4                 Active
              ...
1038    Finished Payment
1039    Finished Payment
1040    Finished Payment
1041    Finished Payment
1042    Finished Payment
Name: LoanStatus, Length: 1043, dtype: object

In [33]:
data['LoanStatus'] = data.LoanStatus.map({'0': 0, 'Active': 1 ,'Blocked': 2,'Finished Payment':3})

In [34]:
# Assuming the order is: 0 < Active < Blocked < Finished Payment
#ordered_labels = {"0": 0, "Active": 1, "Blocked": 2, "Finished Payment": 3}
#data['LoanStatus'] = data['LoanStatus'].map(ordered_labels)

In [35]:
data['LoanStatus'].isnull().sum()

37

In [36]:
data['LoanStatus']

0       1.0
1       1.0
2       NaN
3       1.0
4       1.0
       ...
1038    3.0
1039    3.0
1040    3.0
1041    3.0
1042    3.0
Name: LoanStatus, Length: 1043, dtype: float64

In [37]:
data['LoanStatus'].fillna(data['LoanStatus'].mode()[0], inplace=True)

In [38]:
data['LoanStatus'].isnull().sum()

0

**Declare feature vector and target variable**

In [39]:
X = data.drop(['LoanStatus'], axis=1)

y = data['LoanStatus']

**Split data into separate training and test set**

In [40]:
# split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [41]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((730, 14), (313, 14))

In [42]:
y_train.shape , y_test.shape

((730,), (313,))

In [43]:
y_train

826     3.0
851     3.0
518     3.0
848     3.0
904     3.0
       ...
1033    3.0
763     3.0
835     3.0
559     3.0
684     3.0
Name: LoanStatus, Length: 730, dtype: float64

In [44]:
y_test

731    3.0
408    1.0
564    3.0
650    3.0
752    3.0
      ...
949    3.0
729    3.0
527    3.0
466    1.0
172    1.0
Name: LoanStatus, Length: 313, dtype: float64

In [45]:
X_train

,LoanID,StringID,Product,CustomerGender,Location,Region,TotalPrice,StartDate,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360
826,827,LoanID_827,Product B,NotSpecified,Location 67,Region 6,22950.0,23-05-2019,5000,55,365,5350,7242,22267
851,852,LoanID_852,Product D,Male,Location 44,Region 6,20950.0,11-04-2017,2200,55,365,6351,6643,20267
518,519,LoanID_519,Product D,Male,Location 95,Region 6,19950.0,22-10-2017,2200,55,365,3851,5176,21250
848,849,LoanID_849,Product A,Male,Location 30,Region 1,16300.0,17-06-2016,1000,45,365,5650,5942,15617
904,905,LoanID_905,Product A,Male,Location 10,Region 3,19950.0,07-11-2019,1000,55,365,2000,4392,19267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,1034,LoanID_1034,Product D,Male,Location 181,Region 3,55325.0,18-01-2020,8000,120,365,15851,20143,54642
763,764,LoanID_764,Product A,NotSpecified,Location 267,Region 3,22950.0,08-06-2019,5000,55,365,5300,6992,22267
835,836,LoanID_836,Product B,Female,Location 37,Region 6,16300.0,12-01-2017,1000,45,365,1950,3442,15617
559,560,LoanID_560,Product C,Female,Location 266,Region 1,15300.0,19-03-2017,1000,45,365,10510,10802,15617
684,685,LoanID_685,Product B,Male,Location 174,Region 6,17300.0,16-08-2018,2200,45,365,3251,5013,16617

In [46]:
# check data types in X_train

X_train.dtypes

LoanID              int64
StringID           object
Product            object
CustomerGender     object
Location           object
Region             object
TotalPrice        float64
StartDate          object
Deposit             int64
DailyRate           int64
TotalDaysYr         int64
AmtPaid36           int64
AmtPaid60           int64
AmtPaid360          int64
dtype: object

In [47]:
y_train.dtypes

dtype('float64')

**Feature Engineering**

In [48]:
# display categorical variables

categorical = [col for col in X_train.columns if X_train[col].dtypes == 'O']

categorical

['StringID', 'Product', 'CustomerGender', 'Location', 'Region', 'StartDate']

In [49]:
# display numerical variables

numerical = [col for col in X_train.columns if X_train[col].dtypes != 'O']

numerical

['LoanID',
 'TotalPrice',
 'Deposit',
 'DailyRate',
 'TotalDaysYr',
 'AmtPaid36',
 'AmtPaid60',
 'AmtPaid360']

**Engineering missing values in categorical variables**

In [50]:
# print percentage of missing values in the categorical variables in training set

X_train[categorical].isnull().mean()

StringID          0.0
Product           0.0
CustomerGender    0.0
Location          0.0
Region            0.0
StartDate         0.0
dtype: float64

In [51]:
# print categorical variables with missing data

for col in categorical:
    if X_train[col].isnull().mean()>0:
        print(col, (X_train[col].isnull().mean()))

In [52]:
# check missing values in categorical variables in X_train

X_train[categorical].isnull().sum()

StringID          0
Product           0
CustomerGender    0
Location          0
Region            0
StartDate         0
dtype: int64

In [53]:
# check missing values in categorical variables in X_test

X_test[categorical].isnull().sum()

StringID          0
Product           0
CustomerGender    0
Location          0
Region            0
StartDate         0
dtype: int64

In [54]:
# check missing values in X_train

X_train.isnull().sum()

LoanID            0
StringID          0
Product           0
CustomerGender    0
Location          0
Region            0
TotalPrice        0
StartDate         0
Deposit           0
DailyRate         0
TotalDaysYr       0
AmtPaid36         0
AmtPaid60         0
AmtPaid360        0
dtype: int64

In [55]:
# check missing values in X_test

X_test.isnull().sum()

LoanID            0
StringID          0
Product           0
CustomerGender    0
Location          0
Region            0
TotalPrice        0
StartDate         0
Deposit           0
DailyRate         0
TotalDaysYr       0
AmtPaid36         0
AmtPaid60         0
AmtPaid360        0
dtype: int64

**Encode categorical variables**

In [56]:
# print categorical variables

categorical

['StringID', 'Product', 'CustomerGender', 'Location', 'Region', 'StartDate']

In [57]:
pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.6.3-py2.py3-none-any.whl (81 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.11.4)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.1)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.3.post1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.2)
Installing collected packages: category_encoders
Successfully installed category_encoders-2.6.3

In [58]:
# import category encoders

import category_encoders as ce

In [59]:
encoder = ce.OneHotEncoder(cols=['StringID', 'Product', 'CustomerGender', 'Location', 'Region', 'StartDate'])

In [60]:
X_train = encoder.fit_transform(X_train)

In [61]:
X_test = encoder.transform(X_test)

In [62]:
X_train

,LoanID,StringID_1,StringID_2,StringID_3,StringID_4,StringID_5,StringID_6,StringID_7,StringID_8,StringID_9,...,StartDate_564,StartDate_565,StartDate_566,StartDate_567,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360
826,827,1,0,0,0,0,0,0,0,0,...,0,0,0,0,5000,55,365,5350,7242,22267
851,852,0,1,0,0,0,0,0,0,0,...,0,0,0,0,2200,55,365,6351,6643,20267
518,519,0,0,1,0,0,0,0,0,0,...,0,0,0,0,2200,55,365,3851,5176,21250
848,849,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1000,45,365,5650,5942,15617
904,905,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1000,55,365,2000,4392,19267
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,1034,0,0,0,0,0,0,0,0,0,...,0,0,1,0,8000,120,365,15851,20143,54642
763,764,0,0,0,0,0,0,0,0,0,...,0,0,0,0,5000,55,365,5300,6992,22267
835,836,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1000,45,365,1950,3442,15617
559,560,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1000,45,365,10510,10802,15617
684,685,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2200,45,365,3251,5013,16617

**Feature Scaling**

In [63]:
cols = X_train.columns

In [64]:
cols

Index(['LoanID', 'StringID_1', 'StringID_2', 'StringID_3', 'StringID_4',
       'StringID_5', 'StringID_6', 'StringID_7', 'StringID_8', 'StringID_9',
       ...
       'StartDate_564', 'StartDate_565', 'StartDate_566', 'StartDate_567',
       'Deposit', 'DailyRate', 'TotalDaysYr', 'AmtPaid36', 'AmtPaid60',
       'AmtPaid360'],
      dtype='object', length=1576)

In [65]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [66]:
X_train = pd.DataFrame(X_train, columns=[cols])

In [67]:
X_train

,LoanID,StringID_1,StringID_2,StringID_3,StringID_4,StringID_5,StringID_6,StringID_7,StringID_8,StringID_9,...,StartDate_564,StartDate_565,StartDate_566,StartDate_567,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360
0,0.574458,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2800.0,1.0,0.0,0.815068,0.961538,1.192612
1,0.620562,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.256085,0.731154,0.770449
2,0.006455,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.154643,0.166923,0.977942
3,0.615030,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-1200.0,0.0,0.0,0.947241,0.461538,-0.211082
4,0.718303,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-1200.0,1.0,0.0,-0.660866,-0.134615,0.559367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
725,0.956201,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,5800.0,7.5,0.0,5.441568,5.923462,8.026385
726,0.458276,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2800.0,1.0,0.0,0.793039,0.865385,1.192612
727,0.591056,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-1200.0,0.0,0.0,-0.682895,-0.500000,-0.211082
728,0.082065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,-1200.0,0.0,0.0,3.088446,2.330769,-0.211082
729,0.312586,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.109704,0.104231,0.000000

In [68]:
X_test = pd.DataFrame(X_test, columns=[cols])

In [69]:
X_test

,LoanID,StringID_1,StringID_2,StringID_3,StringID_4,StringID_5,StringID_6,StringID_7,StringID_8,StringID_9,...,StartDate_564,StartDate_565,StartDate_566,StartDate_567,Deposit,DailyRate,TotalDaysYr,AmtPaid36,AmtPaid60,AmtPaid360
0,0.399262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.110144,0.000000,0.000000
1,-0.196404,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5800.0,10.5,0.0,4.872783,5.089615,4.704169
2,0.091286,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.154643,0.269615,0.770449
3,0.249885,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.197819,-0.107308,0.000000
4,0.437990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-1200.0,0.0,0.0,-0.259941,-0.207692,-0.211082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308,0.801291,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2800.0,1.0,0.0,0.793039,0.557692,1.192612
309,0.395574,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.109704,0.000385,0.000000
310,0.023052,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,-1200.0,0.0,0.0,-0.484635,-0.384615,-0.211082
311,-0.089442,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.044498,0.120769,0.520106
312,-0.631627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.154643,0.166923,0.612982

In [70]:
X_test = scaler.transform(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(

**Model training**

In [86]:
# train a Gaussian Naive Bayes classifier on the training set
from sklearn.naive_bayes import GaussianNB


# instantiate the model
gnb = GaussianNB()

In [87]:
gnb

GaussianNB()

In [88]:
# fit the model
gnb.fit(X_train, y_train)

GaussianNB()

**Predict The Result**

In [89]:
y_pred_test = gnb.predict(X_test)

In [90]:
y_pred_test

array([1., 1., 1., 3., 1., 1., 3., 1., 1., 1., 3., 1., 2., 1., 3., 1., 3.,
       1., 1., 1., 1., 1., 1., 2., 1., 1., 3., 1., 1., 1., 1., 1., 1., 2.,
       1., 3., 3., 3., 2., 1., 3., 3., 1., 3., 1., 1., 1., 1., 3., 2., 1.,
       3., 3., 1., 1., 1., 1., 2., 3., 1., 1., 1., 3., 1., 3., 2., 3., 1.,
       1., 1., 2., 3., 1., 3., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 3., 2., 1., 1., 1., 1., 3., 1., 1., 3., 1., 1., 1., 3.,
       3., 1., 1., 2., 3., 3., 3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 1., 1., 3., 1., 1., 3.,
       1., 1., 3., 3., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 2., 1.,
       3., 1., 1., 1., 3., 2., 3., 1., 1., 1., 1., 3., 3., 1., 1., 1., 1.,
       3., 1., 1., 1., 3., 1., 1., 1., 3., 3., 1., 2., 1., 1., 1., 1., 1.,
       1., 3., 1., 1., 3., 3., 3., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 3., 1., 2., 1., 3., 1., 1., 1., 1., 1., 1., 1., 3., 3.,
       1., 1., 1., 3., 1., 1., 3., 3., 3., 3., 1., 1., 1., 3., 3., 1., 1.,
       1., 1., 1., 3., 1., 3., 3., 1., 1., 1., 3., 1., 3., 3., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 2., 2., 2., 1., 1., 3., 1., 1., 2., 3., 1.,
       1., 1., 3., 3., 1., 1., 1., 3., 1., 3., 3., 2., 1., 1., 3., 1., 1.,
       1., 1., 1., 1., 1., 1., 3., 1., 1., 3., 1., 1., 3., 3., 3., 1., 1.,
       1., 1., 1., 1., 3., 2., 1.])

In [91]:
y_pred_train = gnb.predict(X_train)

In [92]:
y_pred_train

array([3., 3., 3., 3., 3., 3., 1., 3., 3., 1., 1., 3., 1., 1., 3., 3., 3.,
       1., 3., 3., 1., 1., 1., 1., 1., 3., 3., 1., 3., 2., 1., 3., 3., 3.,
       3., 1., 1., 1., 3., 1., 1., 1., 1., 1., 1., 2., 3., 2., 1., 1., 1.,
       1., 1., 1., 3., 3., 3., 3., 1., 3., 1., 1., 2., 1., 3., 3., 3., 3.,
       3., 1., 1., 1., 1., 1., 1., 1., 3., 3., 1., 3., 2., 1., 3., 3., 3.,
       1., 3., 3., 1., 1., 1., 3., 2., 1., 1., 1., 2., 3., 1., 1., 1., 2.,
       1., 1., 3., 1., 1., 3., 3., 1., 1., 3., 1., 3., 1., 1., 1., 3., 3.,
       3., 3., 3., 3., 3., 1., 3., 3., 3., 1., 2., 3., 1., 1., 3., 3., 1.,
       3., 3., 3., 1., 3., 1., 3., 3., 1., 3., 1., 3., 3., 3., 3., 1., 1.,
       1., 1., 1., 1., 1., 3., 3., 3., 1., 3., 3., 3., 3., 3., 1., 3., 3.,
       3., 1., 1., 1., 3., 1., 1., 1., 1., 3., 3., 3., 1., 3., 1., 1., 3.,
       3., 2., 1., 3., 3., 3., 3., 3., 1., 3., 3., 1., 1., 3., 3., 3., 1.,
       3., 3., 1., 3., 1., 1., 1., 1., 1., 1., 3., 3., 3., 1., 3., 3., 3.,
       1., 1., 1., 3., 1., 3., 3., 1., 1., 1., 1., 3., 3., 3., 3., 1., 3.,
       3., 1., 3., 3., 3., 1., 3., 1., 3., 3., 1., 3., 3., 1., 1., 1., 3.,
       1., 1., 1., 1., 3., 3., 2., 3., 1., 3., 1., 3., 1., 3., 2., 1., 2.,
       1., 3., 3., 3., 3., 3., 1., 3., 1., 3., 1., 1., 3., 3., 1., 1., 3.,
       1., 1., 1., 3., 3., 2., 3., 1., 3., 2., 1., 1., 3., 3., 3., 3., 1.,
       3., 1., 1., 3., 3., 1., 3., 3., 3., 3., 1., 1., 3., 1., 1., 3., 3.,
       3., 3., 3., 3., 1., 3., 3., 3., 1., 3., 1., 1., 3., 3., 2., 3., 1.,
       2., 1., 3., 3., 3., 2., 3., 3., 3., 1., 3., 1., 3., 1., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 1., 1., 1., 1., 1., 1., 3., 3., 1.,
       3., 1., 3., 3., 1., 3., 3., 3., 3., 1., 1., 3., 3., 3., 1., 1., 1.,
       3., 3., 3., 3., 1., 1., 3., 3., 1., 3., 1., 1., 1., 3., 3., 3., 3.,
       1., 3., 3., 3., 3., 3., 2., 1., 3., 1., 1., 3., 3., 1., 1., 3., 1.,
       1., 1., 1., 3., 3., 3., 1., 1., 1., 1., 3., 3., 3., 3., 1., 1., 1.,
       3., 1., 3., 1., 3., 3., 1., 3., 1., 1., 1., 1., 1., 3., 1., 1., 3.,
       3., 3., 3., 1., 1., 3., 3., 3., 3., 3., 3., 3., 3., 1., 3., 3., 3.,
       3., 3., 3., 1., 3., 1., 1., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       1., 3., 1., 1., 1., 1., 3., 3., 1., 1., 1., 1., 3., 1., 1., 3., 1.,
       3., 3., 3., 3., 3., 1., 1., 1., 1., 3., 3., 3., 3., 3., 1., 1., 1.,
       1., 1., 1., 1., 3., 3., 3., 3., 1., 3., 1., 3., 1., 3., 3., 1., 3.,
       1., 1., 2., 3., 3., 1., 1., 1., 1., 1., 1., 3., 3., 3., 1., 1., 3.,
       3., 1., 1., 1., 3., 3., 1., 3., 3., 1., 1., 1., 1., 3., 1., 3., 1.,
       1., 3., 1., 3., 1., 1., 3., 1., 3., 1., 1., 3., 3., 1., 3., 3., 1.,
       1., 1., 3., 1., 3., 3., 1., 3., 3., 1., 1., 3., 2., 3., 3., 1., 3.,
       3., 1., 3., 3., 1., 3., 1., 1., 3., 3., 1., 3., 1., 2., 3., 1., 3.,
       3., 3., 1., 3., 1., 3., 1., 3., 1., 3., 1., 3., 1., 1., 1., 3., 3.,
       3., 3., 3., 1., 3., 1., 1., 1., 3., 1., 3., 1., 3., 3., 1., 1., 3.,
       3., 1., 1., 3., 1., 1., 1., 3., 2., 3., 3., 1., 3., 3., 1., 3., 1.,
       1., 3., 1., 3., 3., 1., 1., 3., 3., 3., 3., 3., 1., 3., 1., 1., 3.,
       1., 3., 3., 3., 1., 3., 1., 3., 1., 1., 3., 3., 3., 3., 1., 3., 1.,
       3., 3., 3., 1., 1., 3., 3., 1., 3., 3., 1., 3., 3., 3., 3., 3.])

**Check accuracy score**

In [93]:
from sklearn.metrics import accuracy_score

In [94]:
print('Model accuracy test_score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy test_score: 0.4153

In [95]:
print('Model accuracy train_score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Model accuracy train_score: 0.9781